<?php

namespace Mrapps\SymCronBundle\Repository;

/**
 * GroupTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupTaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveGroups()
    {
        return $this->getEntityManager()
            ->createQuery("
        SELECT g,t FROM MrappsSymCronBundle:GroupTask g
        INNER JOIN g.tasks t
        WHERE g.enabled=1
        ORDER BY g.weight, t.weight
        ")->execute();
    }
}
